## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file HW5.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_30 = Integer(30); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_31 = Integer(31); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_32 = Integer(32); _sage_const_6 = Integer(6); _sage_const_33 = Integer(33); _sage_const_7 = Integer(7); _sage_const_34 = Integer(34); _sage_const_8 = Integer(8); _sage_const_43 = Integer(43); _sage_const_47 = Integer(47); _sage_const_50 = Integer(50); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_11 = Integer(11); _sage_const_51 = Integer(51); _sage_const_12 = Integer(12); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_52 = Integer(52); _sage_const_15 = Integer(15); _sage_const_53 = Integer(53); _sage_const_16 = Integer(16); _sage_const_54 = Integer(54); _sage_const_17 = Integer(17)## This file (HW5.sagetex.sage) was *autogenerated* from HW5.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('HW5', version='2020/08/12 v3.5', version_check=True)
_st_.current_tex_line = _sage_const_21 
_st_.blockbegin()
try:
     a,b,c,u,v = var('a,b,c,u,v')
     c1 = u*sin(a)*cos(v)
     c2 = u*sin(a)*sin(v)
     c3 = u*cos(a)
except:
 _st_.goboom(_sage_const_26 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_30 
 _st_.inline(_sage_const_0 , latex(diff(c1,u)))
except:
 _st_.goboom(_sage_const_30 )
try:
 _st_.current_tex_line = _sage_const_30 
 _st_.inline(_sage_const_1 , latex(diff(c2, u)))
except:
 _st_.goboom(_sage_const_30 )
try:
 _st_.current_tex_line = _sage_const_30 
 _st_.inline(_sage_const_2 , latex(diff(c3,u)))
except:
 _st_.goboom(_sage_const_30 )
try:
 _st_.current_tex_line = _sage_const_31 
 _st_.inline(_sage_const_3 , latex(diff(c1,v)))
except:
 _st_.goboom(_sage_const_31 )
try:
 _st_.current_tex_line = _sage_const_31 
 _st_.inline(_sage_const_4 , latex(diff(c2, v)))
except:
 _st_.goboom(_sage_const_31 )
try:
 _st_.current_tex_line = _sage_const_31 
 _st_.inline(_sage_const_5 , latex(diff(c3,v)))
except:
 _st_.goboom(_sage_const_31 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_6 , latex((diff(c1,u)**_sage_const_2  + diff(c2,u)**_sage_const_2  + diff(c3,u)**_sage_const_2 ).full_simplify()))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.current_tex_line = _sage_const_33 
 _st_.inline(_sage_const_7 , latex((diff(c1,u)*diff(c1,v) + diff(c2,u)*diff(c2,v) + diff(c3,u)*diff(c3,v)).full_simplify()))
except:
 _st_.goboom(_sage_const_33 )
try:
 _st_.current_tex_line = _sage_const_34 
 _st_.inline(_sage_const_8 , latex((diff(c1,v)**_sage_const_2  + diff(c2,v)**_sage_const_2  + diff(c3,v)**_sage_const_2 ).full_simplify()))
except:
 _st_.goboom(_sage_const_34 )
_st_.current_tex_line = _sage_const_43 
_st_.blockbegin()
try:
     c1 = _sage_const_2 *u/(_sage_const_1  + u**_sage_const_2  + v**_sage_const_2 )
     c2 = _sage_const_2 *v/(_sage_const_1  + u**_sage_const_2  + v**_sage_const_2 )
     c3 = (-_sage_const_1  + u**_sage_const_2  + v**_sage_const_2 )/(_sage_const_1  + u**_sage_const_2  + v**_sage_const_2 )
except:
 _st_.goboom(_sage_const_47 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_50 
 _st_.inline(_sage_const_9 , latex(diff(c1,u)))
except:
 _st_.goboom(_sage_const_50 )
try:
 _st_.current_tex_line = _sage_const_50 
 _st_.inline(_sage_const_10 , latex(diff(c2, u)))
except:
 _st_.goboom(_sage_const_50 )
try:
 _st_.current_tex_line = _sage_const_50 
 _st_.inline(_sage_const_11 , latex(diff(c3,u)))
except:
 _st_.goboom(_sage_const_50 )
try:
 _st_.current_tex_line = _sage_const_51 
 _st_.inline(_sage_const_12 , latex(diff(c1,v)))
except:
 _st_.goboom(_sage_const_51 )
try:
 _st_.current_tex_line = _sage_const_51 
 _st_.inline(_sage_const_13 , latex(diff(c2, v)))
except:
 _st_.goboom(_sage_const_51 )
try:
 _st_.current_tex_line = _sage_const_51 
 _st_.inline(_sage_const_14 , latex(diff(c3,v)))
except:
 _st_.goboom(_sage_const_51 )
try:
 _st_.current_tex_line = _sage_const_52 
 _st_.inline(_sage_const_15 , latex((diff(c1,u)**_sage_const_2  + diff(c2,u)**_sage_const_2  + diff(c3,u)**_sage_const_2 ).full_simplify()))
except:
 _st_.goboom(_sage_const_52 )
try:
 _st_.current_tex_line = _sage_const_53 
 _st_.inline(_sage_const_16 , latex((diff(c1,u)*diff(c1,v) + diff(c2,u)*diff(c2,v) + diff(c3,u)*diff(c3,v)).full_simplify()))
except:
 _st_.goboom(_sage_const_53 )
try:
 _st_.current_tex_line = _sage_const_54 
 _st_.inline(_sage_const_17 , latex((diff(c1,v)**_sage_const_2  + diff(c2,v)**_sage_const_2  + diff(c3,v)**_sage_const_2 ).full_simplify()))
except:
 _st_.goboom(_sage_const_54 )
_st_.endofdoc()

