## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file HW5.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_27 = Integer(27); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_32 = Integer(32); _sage_const_35 = Integer(35); _sage_const_0 = Integer(0); _sage_const_36 = Integer(36); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_37 = Integer(37); _sage_const_6 = Integer(6); _sage_const_38 = Integer(38); _sage_const_7 = Integer(7); _sage_const_39 = Integer(39); _sage_const_8 = Integer(8)## This file (HW5.sagetex.sage) was *autogenerated* from HW5.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('HW5', version='2020/08/12 v3.5', version_check=True)
_st_.current_tex_line = _sage_const_27 
_st_.blockbegin()
try:
     a,b,c,u,v = var('a,b,c,u,v')
     c1 = _sage_const_2 *u/(_sage_const_1  + u**_sage_const_2  + v**_sage_const_2 )
     c2 = _sage_const_2 *v/(_sage_const_1  + u**_sage_const_2  + v**_sage_const_2 )
     c3 = (-_sage_const_1  + u**_sage_const_2  + v**_sage_const_2 )/(_sage_const_1  + u**_sage_const_2  + v**_sage_const_2 )
except:
 _st_.goboom(_sage_const_32 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_0 , latex(diff(c1,u)))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_1 , latex(diff(c2, u)))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_2 , latex(diff(c3,u)))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_36 
 _st_.inline(_sage_const_3 , latex(diff(c1,v)))
except:
 _st_.goboom(_sage_const_36 )
try:
 _st_.current_tex_line = _sage_const_36 
 _st_.inline(_sage_const_4 , latex(diff(c2, v)))
except:
 _st_.goboom(_sage_const_36 )
try:
 _st_.current_tex_line = _sage_const_36 
 _st_.inline(_sage_const_5 , latex(diff(c3,v)))
except:
 _st_.goboom(_sage_const_36 )
try:
 _st_.current_tex_line = _sage_const_37 
 _st_.inline(_sage_const_6 , latex((diff(c1,u)**_sage_const_2  + diff(c2,u)**_sage_const_2  + diff(c3,u)**_sage_const_2 ).full_simplify()))
except:
 _st_.goboom(_sage_const_37 )
try:
 _st_.current_tex_line = _sage_const_38 
 _st_.inline(_sage_const_7 , latex((diff(c1,u)*diff(c1,v) + diff(c2,u)*diff(c2,v) + diff(c3,u)*diff(c3,v)).full_simplify()))
except:
 _st_.goboom(_sage_const_38 )
try:
 _st_.current_tex_line = _sage_const_39 
 _st_.inline(_sage_const_8 , latex((diff(c1,v)**_sage_const_2  + diff(c2,v)**_sage_const_2  + diff(c3,v)**_sage_const_2 ).full_simplify()))
except:
 _st_.goboom(_sage_const_39 )
_st_.endofdoc()

