## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file HW7.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_76 = Integer(76); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_83 = Integer(83); _sage_const_91 = Integer(91); _sage_const_0 = Integer(0); _sage_const_93 = Integer(93); _sage_const_102 = Integer(102); _sage_const_109 = Integer(109); _sage_const_110 = Integer(110); _sage_const_112 = Integer(112)## This file (HW7.sagetex.sage) was *autogenerated* from HW7.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('HW7', version='2020/08/12 v3.5', version_check=True)
_st_.current_tex_line = _sage_const_76 
_st_.blockbegin()
try:
 forget()
 M = Manifold(_sage_const_3 , 'R^3', start_index=_sage_const_1 )
 c_spher = M.chart(r'a:(0,+oo) b:(0,pi):\theta h:(-oo,+oo)', names=('a', 'b', 'h',)); (a, b, h,) = c_spher._first_ngens(3)
 g = M.metric('g')
 g[_sage_const_1 ,_sage_const_1 ], g[_sage_const_2 ,_sage_const_2 ], g[_sage_const_3 ,_sage_const_3 ] = _sage_const_1 , a**_sage_const_2 , _sage_const_1 
 nab = g.connection(name='Gamma', latex_name=r'\Gamma')
except:
 _st_.goboom(_sage_const_83 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.inline(_sage_const_0 , latex(g.display()))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_93 
 _st_.inline(_sage_const_1 , latex(nab.display()))
except:
 _st_.goboom(_sage_const_93 )
_st_.current_tex_line = _sage_const_102 
_st_.blockbegin()
try:
     forget()
     M = Manifold(_sage_const_3 , 'R^3', start_index=_sage_const_1 )
     c_spher = M.chart(r'r:(0,+oo) th:(0,pi):\theta ph:(0,2*pi):\phi', names=('r', 'th', 'ph',)); (r, th, ph,) = c_spher._first_ngens(3)
     g = M.metric('g')
     g[_sage_const_1 ,_sage_const_1 ], g[_sage_const_2 ,_sage_const_2 ], g[_sage_const_3 ,_sage_const_3 ] = _sage_const_1 , r**_sage_const_2  , (r*sin(th))**_sage_const_2 
     nab = g.connection(name='Gamma', latex_name=r'\Gamma')
except:
 _st_.goboom(_sage_const_109 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_110 
 _st_.inline(_sage_const_2 , latex(g.display()))
except:
 _st_.goboom(_sage_const_110 )
try:
 _st_.current_tex_line = _sage_const_112 
 _st_.inline(_sage_const_3 , latex(nab.display()))
except:
 _st_.goboom(_sage_const_112 )
_st_.endofdoc()

